### ISSUE TITLE
Support gridfs

### ISSUE THREAD

**Issue by tomerghelber** [mongodb/morphia#885] opened 2016-01-23 10:10 UTC
When using GridFS, I found myself need to load by hand.
It could be great if there was an annotation for that which would load it (lazy and not).

I can post here my code, but it works external from morphia.
I load it it with your API for pre-save and post-load. For delete i wrote my own function. I created a new annotation GridFsFile that work with your Transient and even have a converter from byte[] to an Object.

**Comment by evanchooly** [comment] 2016-06-13 21:03
duplicate of #153

**Closed by evanchooly** 2016-06-13 21:03 UTC
