### ISSUE TITLE
Unable to add multiple accumulators in an aggregate grouping function call

### ISSUE THREAD

**Issue by Deviraja** [mongodb/morphia#918] opened 2016-04-06 15:34 UTC
db.profit_and_loss.aggregate(
			    [
			        {
			            $group : {
			                _id : { breakPeriodDate: "$breakPeriodStartDate", orderEntityId: "$orderEntityId"  },
			                sum: { $sum: {$add: ["$amountFromTBInDouble","$amountFromParentPNLInDouble"]} },
			                count: { $sum: 1 }
			            }
			        }
			    ]
			)		

in the above example, i am adding two properties **amountFromTBInDouble** and **amountFromParentPNLInDouble** before I pass the result to the sum operator.

Now in Morphia, I try the following and it fails because the Accumulator object is expected to be a field. 

		AggregationPipeline pipeline = datastore
	            .createAggregation(VedaProfitAndLoss.class)
				 .match(
						 datastore.createQuery(VedaProfitAndLoss.class)
						 .field("orderEntityId").equal(_orderEntityId)
						 .field("breakPeriodStartDate").equal(_breakPeriod.breakPeriodStartDate)
						 .field("breakPeriodEndDate").equal(_breakPeriod.breakPeriodEndDate)
						 .field("hasBeenSpeciallyAllocated").equal(false)
						 .field("hasBeenHotIssueAllocated").equal(false)
				  )
	            .group(
	                Group.id(grouping("breakPeriodEndDate", "breakPeriodEndDate"),
	                         grouping("orderEntityId", "orderEntityId")),
	                         grouping("summation", new Accumulator("$sum", new Accumulator("$add", "amountFromTBInDouble,amountFromParentPNLInDouble"))))
	                ;

**Comment by evanchooly** [comment] 2016-04-06 15:43
This looks like it could be a duplicate of #896.  Can you try using the 1.2.0-SNAPSHOT and confirm whether that fix works for you or not?

**Comment by Deviraja** [comment] 2016-04-06 16:09
#896 speaks about the inability to create a group with multiple properties even though the native query generated is correct. In my example above, I have a similar condition which is working fine. What does not work for me is the nesting of multiple Accumulators. 

Where can I get the 1.2.0-SNAPSHOT build from? Maven is unable to resolve dependencies for this version.

**Comment by Deviraja** [comment] 2016-04-06 16:11
got the build. will check it for a resolution.

**Comment by Deviraja** [comment] 2016-04-06 16:34
Tested and it does not work. The expression "**{$add: ["$amountFromTBInDouble","$amountFromParentPNLInDouble"]}**" embedded within the **$sum** operator does not work when translated into Morphia code. 

    db.profit_and_loss.aggregate(
            [
                {
                    $group : {
                        _id : { breakPeriodDate: "$breakPeriodStartDate", orderEntityId: "$orderEntityId"  },
                        sum: { $sum: {$add: ["$amountFromTBInDouble","$amountFromParentPNLInDouble"]} },
                        count: { $sum: 1 }
                    }
                }
            ]
        )       


    AggregationPipeline pipeline = datastore
            .createAggregation(VedaProfitAndLoss.class)
             .match(
                     datastore.createQuery(VedaProfitAndLoss.class)
                     .field("orderEntityId").equal(_orderEntityId)
                     .field("breakPeriodStartDate").equal(_breakPeriod.breakPeriodStartDate)
                     .field("breakPeriodEndDate").equal(_breakPeriod.breakPeriodEndDate)
                     .field("hasBeenSpeciallyAllocated").equal(false)
                     .field("hasBeenHotIssueAllocated").equal(false)
              )
            .group(
                Group.id(grouping("breakPeriodEndDate", "breakPeriodEndDate"),
                         grouping("orderEntityId", "orderEntityId")),
                         grouping("summation", new Accumulator("$sum", new Accumulator("$add", "amountFromTBInDouble,amountFromParentPNLInDouble"))))
                ;

**Comment by evanchooly** [comment] 2016-06-24 16:50
See [here](https://github.com/mongodb/morphia/blob/02762d9c6bc33427668e201ccca3a6c918652394/morphia/src/test/java/org/mongodb/morphia/aggregation/AggregationTest.java#L436-L436) for how to do this.

**Closed** 2016-06-24 16:50 UTC
