### ISSUE TITLE
NoSuchMethodException: java.math.Bigecimal

### ISSUE THREAD

**Issue by gabroglio** [mongodb/morphia#769] opened 2015-05-12 15:20 UTC
When trying to load numeric data in a BigDecimal defined object this issue is thrown:

Caused by: java.lang.NoSuchMethodException: java.math.BigDecimal.<init>()
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.getDeclaredConstructor(Unknown Source)
	at org.mongodb.morphia.mapping.DefaultCreator.getNoArgsConstructor(DefaultCreator.java:43)

This happens with versions: 1.0.0-rc0 and 0.111

**Comment by evanchooly** [comment] 2015-05-12 15:27
BigDecimal is not a supported type.  There are a number of differing ways to map this and which one to use is fairly dependent on its intended use.  See this [thread](https://groups.google.com/forum/#!searchin/morphia/Bigecimal/morphia/RJy8HIRXOL0/SxGOTEKmKiwJ) on the mailing list for details.

**Comment by evanchooly** [comment] 2015-05-12 15:27
BigDecimal is not a supported type.  There are a number of differing ways to map this and which one to use is fairly dependent on its intended use.  See this [thread](https://groups.google.com/forum/#!searchin/morphia/Bigecimal/morphia/RJy8HIRXOL0/SxGOTEKmKiwJ) on the mailing list for details.

**Comment by evanchooly** [comment] 2015-05-12 15:27
Duplicate of #411

**Closed by evanchooly** 2015-05-12 15:27 UTC
