### ISSUE TITLE
A type could not be found for the field null.null

### ISSUE THREAD

**Issue by AceSpades** [mongodb/morphia#779] opened 2015-05-16 21:06 UTC
If I create this class

<pre>
@Entity
public class A&#60V&#62 {
  @Id
  private int id;
  private Collection&#60V&#62 mappingErrorField;
}
</pre>
when i call morphia.map(A.class) i get this error:

<pre>
Exception in thread "main" org.mongodb.morphia.mapping.MappingException: A type could not be found for the field null.null
    at org.mongodb.morphia.mapping.MappedField.discoverType(MappedField.java:211)
    at org.mongodb.morphia.mapping.MappedField.<init>(MappedField.java:101)
    at org.mongodb.morphia.mapping.EphemeralMappedField.<init>(EphemeralMappedField.java:36)
    at org.mongodb.morphia.mapping.MappedField.discoverType(MappedField.java:189)
    at org.mongodb.morphia.mapping.MappedField.discover(MappedField.java:117)
    at org.mongodb.morphia.mapping.MappedField.<init>(MappedField.java:95)
    at org.mongodb.morphia.mapping.MappedClass.discover(MappedClass.java:214)
    at org.mongodb.morphia.mapping.MappedClass.<init>(MappedClass.java:145)
    at org.mongodb.morphia.mapping.Mapper.addMappedClass(Mapper.java:160)
    at org.mongodb.morphia.Morphia.map(Morphia.java:67)
</pre>

**Comment by evanchooly** [comment] 2015-05-18 15:53
What version are you using?

**Comment by AceSpades** [comment] 2015-05-19 07:32
1.0.0-rc0

**Comment by evanchooly** [comment] 2015-05-20 15:08
This is a duplicate of #552, actually.  There is work planned to fix this but it won't make the 1.0 release.

**Closed by evanchooly** 2015-05-20 15:08 UTC

**Comment by harmeetsingh0013** [comment] 2015-06-20 17:16
Hey @evanchooly how can i use generics with MongoMorphia? How i resolve this issue?

**Comment by harmeetsingh0013** [comment] 2015-06-20 17:17
Here is my code: 

`
ParameterizedType parameterizedType = (ParameterizedType) getClass().getGenericSuperclass();
type = (Class<T>) parameterizedType.getActualTypeArguments()[0];
(List<T>) getDataStore().createQuery(type.getClass()).asList();
`

**Comment by harmeetsingh0013** [comment] 2015-06-20 17:33
Hey @evanchooly i was resolve this problem using following code: 
`(List<T>) getDataStore().createQuery(Class.forName(type.getTypeName())).asList()`
