### ISSUE TITLE
ArrayOutOfBoundException when setting a Map field

### ISSUE THREAD

**Issue by detonator413** [mongodb/morphia#1115] opened 2017-01-04 16:58 UTC
I have an entity "Account" with a "props" field that is Map<String, String>. When I'm trying to set this field via:

> UpdateOperations<Account> ops = createUpdateOperations();
  ops.set("props", new HashMap<String, String>());

I'm getting:

> at java.util.Arrays$ArrayList.get(Arrays.java:3841)
	at org.mongodb.morphia.internal.PathTarget.next(PathTarget.java:96)
	at org.mongodb.morphia.internal.PathTarget.resolve(PathTarget.java:115)
	at org.mongodb.morphia.internal.PathTarget.getTarget(PathTarget.java:90)
	at org.mongodb.morphia.query.UpdateOpsImpl.add(UpdateOpsImpl.java:279)
	at org.mongodb.morphia.query.UpdateOpsImpl.set(UpdateOpsImpl.java:223)

The reason for it that PathTarget contains:
>   if (!field.isMap()) {
          translate(field.getNameToStore());
     } else {
          next();  // consume the map key segment
     }

So the field is actually a map and `PathTarget` contains only 1 segment which has been already consumed by the time when `next()` is called from the `else` clause. 

The issues occurs with 1.3.0 and does not appear on 1.2.0 and earlier.

**Comment by evanchooly** [comment] 2017-01-04 17:04
duplicate of #1089

**Closed by evanchooly** 2017-01-04 17:04 UTC
