### ISSUE TITLE
arrayOutOfBounds exception in PathTarget.resolve()

### ISSUE THREAD

**Issue by ymmark0** [mongodb/morphia#1100] opened 2016-12-07 17:16 UTC
The method pathTarget.resolve() is as follows:

`
private void resolve() {
        context = this.root;
        position = 0;
        MappedField field = null;
        while (hasNext()) {
            String segment = next();

            if (segment.equals("$") || segment.matches("[0-9]+")) {  // array operator
                segment = next();
            }
            field = resolveField(segment);

            if (field != null) {
                if (!field.isMap()) {
                    translate(field.getNameToStore());
                } else {
                    next();  // consume the map key segment
                }
            } else {
                if (validateNames) {
                    throw new ValidationException(format("Could not resolve path '%s' against '%s'.", join(segments, '.'),
                                                         root.getClazz().getName()));
                }
            }
        }
        target = field;
        resolved = true;
    }
`

as you can see, it starts a loop with while(hasNext()) and then proceeds to call next in three separate locations.  I'm finding that the third next() is being called leading to an arrayOutOfBounds exception related to update operations.

**Comment by evanchooly** [comment] 2016-12-07 18:03
duplicate of #1089 

good catch, though.

**Closed by evanchooly** 2016-12-07 18:03 UTC

**Comment by ymmark0** [comment] 2016-12-07 19:32
drat - I was actually pretty excited that I found a bug ) 
sorry for missing the duplicate....

**Comment by evanchooly** [comment] 2016-12-07 19:41
no worries.
