### ISSUE TITLE
Caching of embedded entities

### ISSUE THREAD

**Issue by kzmeyao** [mongodb/morphia#613] opened 2014-05-07 20:42 UTC
When we retrieve documents that happen to have different versions of an embedded document (sharing the same id), we are running into an issue where morphia's mapper returns the same embedded object when they are clearly different in mongo. A quick search led me to someone else with the exact same issue as mine, but it never gained any traction:

https://code.google.com/p/morphia/issues/detail?id=281

I tried it with the latest version of morphia, but it doesn't seem like it was ever fixed.
Is this a bug or is it a limitation caused by our design?

**Comment by heltjm** [comment] 2015-03-02 19:20
I'm running into this same issue.  Is there a resolution for this or a way to disable this caching?  Much appreciated.

**Comment by SilentGert** [comment] 2015-03-31 07:30
There is a solution for the issue if your nested document just lives within another document and not in an own collection. The nested document has to be annotated with `@Embedded` and it cannot use the `@Id` annotation. 
```
@Embedded
public class MyDocument {

    private ObjectId id;

    private String value;

    public ObjectId getId() {
        return id;
    }

    public void setId(ObjectId id) {
        this.id = id;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
```
Then the test case above passes. However, you will not be able to store the nested document in a separate collection.

**Comment by heltjm** [comment] 2015-03-31 15:05
Yes, the problem is that I need to store these documents both in their own collection and as embedded objects since I am keeping revisions of the object.  My solution was to put the following on the object that contained the embedded object.
```
@PreSave
private void preSave(DBObject revisionObject) {

  if (revisionObject.containsField("embeddedObject")) {
    DBObject embeddedObject = (DBObject) revisionObject.get("embeddedObject");
    Object embeddedObjectId = embeddedObject.removeField("_id");
    revisionObject.put("embeddedObjectId", embeddedObjectId);
  }
}

@PostLoad
private void postLoad() {

  if (embeddedObject != null) {
    embeddedObject.setId(embeddedObjectId);
  }
}
```

It's a hack, but it keeps the rest of the system from needing to worry about it.

**Comment by evanchooly** [comment] 2015-03-31 15:22
Are you just trying to store a historical archive of document state?

**Comment by heltjm** [comment] 2015-03-31 18:19
Yes, exactly

**Comment by evanchooly** [comment] 2015-03-31 18:20
You might want to check out [lariat](https://github.com/evanchooly/lariat) then.

**Comment by heltjm** [comment] 2015-03-31 18:25
Interesting, I'll take a look.  Thank you!

**Comment by evanchooly** [comment] 2016-12-07 18:05
I'm going to close this out since embedded documents aren't their own distinct entities (no unique ID, e.g., as far as the database is concerned.)  Adding caching on this level would be both a misfeature and overly complicated for the gain.

**Closed by evanchooly** 2016-12-07 18:05 UTC
Labels: wontfix
